package cli

import "time"

const (
	defaultConcurrency = 4
	defaultRetries     = 0
	defaultService     = "chatgpt"
	defaultSourceDir   = "./locales/en"
	defaultTargetDir   = "./locales"
	defaultSourceLang  = "en"
	defaultTargetLang  = "es,fr,de"
	defaultConfigPath  = ".i18n-translator.yaml"
	defaultExamplePath = ".i18n-translator.example.yaml"
)

var (
	defaultRetryDelay = time.Second
	defaultTimeout    time.Duration
	defaultConfigBody = "" +
		"# Generated by: i18n-ai-translator init\n" +
		"service: gemini\n" +
		"api_key: your-api-key\n" +
		"model: gemini-2.0-flash\n" +
		"url: \"\"\n" +
		"from: en\n" +
		"to: ru,es,fr\n" +
		"source: ./locales/en\n" +
		"target: ./locales\n" +
		"concurrency: 6\n" +
		"dry_run: false\n" +
		"list_files: false\n" +
		"skip_existing: false\n" +
		"fail_fast: false\n" +
		"retries: 2\n" +
		"retry_delay: 1s\n" +
		"timeout: 60s\n"
)

type TranslationService interface {
	Translate(text, sourceLang, targetLang string) (string, error)
}

type translator struct {
	service TranslationService
}

type translateJob struct {
	sourcePath string
	targetPath string
	relPath    string
	lang       string
}

type runOptions struct {
	retries    int
	retryDelay time.Duration
	failFast   bool
}

type runStats struct {
	Total              int
	Succeeded          int
	Failed             int
	Skipped            int
	Retried            int
	FailFastTriggered  bool
	FailFastFirstError string
}

type appConfig struct {
	Service      string `yaml:"service"`
	Model        string `yaml:"model"`
	Source       string `yaml:"source"`
	Target       string `yaml:"target"`
	From         string `yaml:"from"`
	To           string `yaml:"to"`
	APIKey       string `yaml:"api_key"`
	APIKeyAlt    string `yaml:"api-key"`
	URL          string `yaml:"url"`
	Concurrency  int    `yaml:"concurrency"`
	DryRun       bool   `yaml:"dry_run"`
	ListFiles    bool   `yaml:"list_files"`
	SkipExisting bool   `yaml:"skip_existing"`
	FailFast     bool   `yaml:"fail_fast"`
	Retries      int    `yaml:"retries"`
	RetryDelay   string `yaml:"retry_delay"`
	Timeout      string `yaml:"timeout"`
}

func (c appConfig) apiKey() string {
	if c.APIKey != "" {
		return c.APIKey
	}
	return c.APIKeyAlt
}
